version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: similarweb
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
volumes:
  mongodata:
    driver: local
